/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : AlertId,
  'isAcknowledged' : boolean,
  'message' : string,
  'timestamp' : Timestamp,
  'severity' : AlertSeverity,
}
export type AlertId = bigint;
export type AlertSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface DetectedObject {
  'x' : number,
  'y' : number,
  'height' : number,
  'width' : number,
  'confidence' : number,
  'objectType' : string,
}
export interface DetectionResult {
  'totalCount' : bigint,
  'objects' : Array<DetectedObject>,
  'timestamp' : Timestamp,
}
export interface DeviceStatus {
  'batteryLevel' : bigint,
  'raspberryPiOnline' : boolean,
  'sensorWorking' : boolean,
  'lastHeartbeat' : Timestamp,
  'wifiConnected' : boolean,
}
export interface Location {
  'latitude' : number,
  'waterBodyName' : string,
  'description' : string,
  'longitude' : number,
}
export type PollutionClassification = { 'HighlyPolluted' : null } |
  { 'Moderate' : null } |
  { 'Clean' : null };
export interface PollutionHistoryEntry {
  'score' : bigint,
  'timestamp' : Timestamp,
}
export type PollutionLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface PollutionScore {
  'level' : PollutionLevel,
  'score' : bigint,
  'timestamp' : Timestamp,
  'classification' : PollutionClassification,
}
export interface SensorHistoryEntry {
  'ph' : number,
  'tds' : number,
  'turbidity' : number,
  'timestamp' : Timestamp,
}
export interface SensorReading {
  'ph' : number,
  'tds' : number,
  'turbidity' : number,
  'timestamp' : Timestamp,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<[AlertId], boolean>,
  'addAlert' : ActorMethod<[string, AlertSeverity], AlertId>,
  'addDetectionResult' : ActorMethod<[Array<DetectedObject>], undefined>,
  'getActiveAlerts' : ActorMethod<[], Array<Alert>>,
  'getCurrentSensorReading' : ActorMethod<[], [] | [SensorReading]>,
  'getDeviceStatus' : ActorMethod<[], DeviceStatus>,
  'getLatestDetections' : ActorMethod<[], [] | [DetectionResult]>,
  'getLocation' : ActorMethod<[], Location>,
  'getPollutionHistory' : ActorMethod<[], Array<PollutionHistoryEntry>>,
  'getPollutionScore' : ActorMethod<[], [] | [PollutionScore]>,
  'getSensorHistory' : ActorMethod<[], Array<SensorHistoryEntry>>,
  'updateDeviceStatus' : ActorMethod<
    [boolean, boolean, bigint, boolean],
    undefined
  >,
  'updateSensorReading' : ActorMethod<[number, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];