/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertId = IDL.Nat;
export const AlertSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const DetectedObject = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'width' : IDL.Float64,
  'confidence' : IDL.Float64,
  'objectType' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Alert = IDL.Record({
  'id' : AlertId,
  'isAcknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'severity' : AlertSeverity,
});
export const SensorReading = IDL.Record({
  'ph' : IDL.Float64,
  'tds' : IDL.Float64,
  'turbidity' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const DeviceStatus = IDL.Record({
  'batteryLevel' : IDL.Nat,
  'raspberryPiOnline' : IDL.Bool,
  'sensorWorking' : IDL.Bool,
  'lastHeartbeat' : Timestamp,
  'wifiConnected' : IDL.Bool,
});
export const DetectionResult = IDL.Record({
  'totalCount' : IDL.Nat,
  'objects' : IDL.Vec(DetectedObject),
  'timestamp' : Timestamp,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'waterBodyName' : IDL.Text,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const PollutionHistoryEntry = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const PollutionLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const PollutionClassification = IDL.Variant({
  'HighlyPolluted' : IDL.Null,
  'Moderate' : IDL.Null,
  'Clean' : IDL.Null,
});
export const PollutionScore = IDL.Record({
  'level' : PollutionLevel,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'classification' : PollutionClassification,
});
export const SensorHistoryEntry = IDL.Record({
  'ph' : IDL.Float64,
  'tds' : IDL.Float64,
  'turbidity' : IDL.Float64,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func([AlertId], [IDL.Bool], []),
  'addAlert' : IDL.Func([IDL.Text, AlertSeverity], [AlertId], []),
  'addDetectionResult' : IDL.Func([IDL.Vec(DetectedObject)], [], []),
  'getActiveAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getCurrentSensorReading' : IDL.Func([], [IDL.Opt(SensorReading)], ['query']),
  'getDeviceStatus' : IDL.Func([], [DeviceStatus], ['query']),
  'getLatestDetections' : IDL.Func([], [IDL.Opt(DetectionResult)], ['query']),
  'getLocation' : IDL.Func([], [Location], ['query']),
  'getPollutionHistory' : IDL.Func(
      [],
      [IDL.Vec(PollutionHistoryEntry)],
      ['query'],
    ),
  'getPollutionScore' : IDL.Func([], [IDL.Opt(PollutionScore)], ['query']),
  'getSensorHistory' : IDL.Func([], [IDL.Vec(SensorHistoryEntry)], ['query']),
  'updateDeviceStatus' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateSensorReading' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertId = IDL.Nat;
  const AlertSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DetectedObject = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'width' : IDL.Float64,
    'confidence' : IDL.Float64,
    'objectType' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Alert = IDL.Record({
    'id' : AlertId,
    'isAcknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'severity' : AlertSeverity,
  });
  const SensorReading = IDL.Record({
    'ph' : IDL.Float64,
    'tds' : IDL.Float64,
    'turbidity' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const DeviceStatus = IDL.Record({
    'batteryLevel' : IDL.Nat,
    'raspberryPiOnline' : IDL.Bool,
    'sensorWorking' : IDL.Bool,
    'lastHeartbeat' : Timestamp,
    'wifiConnected' : IDL.Bool,
  });
  const DetectionResult = IDL.Record({
    'totalCount' : IDL.Nat,
    'objects' : IDL.Vec(DetectedObject),
    'timestamp' : Timestamp,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'waterBodyName' : IDL.Text,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const PollutionHistoryEntry = IDL.Record({
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const PollutionLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const PollutionClassification = IDL.Variant({
    'HighlyPolluted' : IDL.Null,
    'Moderate' : IDL.Null,
    'Clean' : IDL.Null,
  });
  const PollutionScore = IDL.Record({
    'level' : PollutionLevel,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'classification' : PollutionClassification,
  });
  const SensorHistoryEntry = IDL.Record({
    'ph' : IDL.Float64,
    'tds' : IDL.Float64,
    'turbidity' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func([AlertId], [IDL.Bool], []),
    'addAlert' : IDL.Func([IDL.Text, AlertSeverity], [AlertId], []),
    'addDetectionResult' : IDL.Func([IDL.Vec(DetectedObject)], [], []),
    'getActiveAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getCurrentSensorReading' : IDL.Func(
        [],
        [IDL.Opt(SensorReading)],
        ['query'],
      ),
    'getDeviceStatus' : IDL.Func([], [DeviceStatus], ['query']),
    'getLatestDetections' : IDL.Func([], [IDL.Opt(DetectionResult)], ['query']),
    'getLocation' : IDL.Func([], [Location], ['query']),
    'getPollutionHistory' : IDL.Func(
        [],
        [IDL.Vec(PollutionHistoryEntry)],
        ['query'],
      ),
    'getPollutionScore' : IDL.Func([], [IDL.Opt(PollutionScore)], ['query']),
    'getSensorHistory' : IDL.Func([], [IDL.Vec(SensorHistoryEntry)], ['query']),
    'updateDeviceStatus' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateSensorReading' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };