/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    waterBodyName: string;
    description: string;
    longitude: number;
}
export type Timestamp = bigint;
export type AlertId = bigint;
export interface SensorHistoryEntry {
    ph: number;
    tds: number;
    turbidity: number;
    timestamp: Timestamp;
}
export interface DetectionResult {
    totalCount: bigint;
    objects: Array<DetectedObject>;
    timestamp: Timestamp;
}
export interface DeviceStatus {
    batteryLevel: bigint;
    raspberryPiOnline: boolean;
    sensorWorking: boolean;
    lastHeartbeat: Timestamp;
    wifiConnected: boolean;
}
export interface PollutionHistoryEntry {
    score: bigint;
    timestamp: Timestamp;
}
export interface PollutionScore {
    level: PollutionLevel;
    score: bigint;
    timestamp: Timestamp;
    classification: PollutionClassification;
}
export interface SensorReading {
    ph: number;
    tds: number;
    turbidity: number;
    timestamp: Timestamp;
}
export interface DetectedObject {
    x: number;
    y: number;
    height: number;
    width: number;
    confidence: number;
    objectType: string;
}
export interface Alert {
    id: AlertId;
    isAcknowledged: boolean;
    message: string;
    timestamp: Timestamp;
    severity: AlertSeverity;
}
export enum AlertSeverity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum PollutionClassification {
    HighlyPolluted = "HighlyPolluted",
    Moderate = "Moderate",
    Clean = "Clean"
}
export enum PollutionLevel {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export interface backendInterface {
    acknowledgeAlert(id: AlertId): Promise<boolean>;
    addAlert(message: string, severity: AlertSeverity): Promise<AlertId>;
    addDetectionResult(objects: Array<DetectedObject>): Promise<void>;
    getActiveAlerts(): Promise<Array<Alert>>;
    getCurrentSensorReading(): Promise<SensorReading | null>;
    getDeviceStatus(): Promise<DeviceStatus>;
    getLatestDetections(): Promise<DetectionResult | null>;
    getLocation(): Promise<Location>;
    getPollutionHistory(): Promise<Array<PollutionHistoryEntry>>;
    getPollutionScore(): Promise<PollutionScore | null>;
    getSensorHistory(): Promise<Array<SensorHistoryEntry>>;
    updateDeviceStatus(raspberryPiOnline: boolean, sensorWorking: boolean, batteryLevel: bigint, wifiConnected: boolean): Promise<void>;
    updateSensorReading(ph: number, turbidity: number, tds: number): Promise<void>;
}
import type { Alert as _Alert, AlertId as _AlertId, AlertSeverity as _AlertSeverity, DetectionResult as _DetectionResult, PollutionClassification as _PollutionClassification, PollutionLevel as _PollutionLevel, PollutionScore as _PollutionScore, SensorReading as _SensorReading, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: AlertId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async addAlert(arg0: string, arg1: AlertSeverity): Promise<AlertId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(arg0, to_candid_AlertSeverity_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(arg0, to_candid_AlertSeverity_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addDetectionResult(arg0: Array<DetectedObject>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDetectionResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDetectionResult(arg0);
            return result;
        }
    }
    async getActiveAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlerts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlerts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentSensorReading(): Promise<SensorReading | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentSensorReading();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentSensorReading();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeviceStatus(): Promise<DeviceStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceStatus();
            return result;
        }
    }
    async getLatestDetections(): Promise<DetectionResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestDetections();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestDetections();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(): Promise<Location> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation();
            return result;
        }
    }
    async getPollutionHistory(): Promise<Array<PollutionHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPollutionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPollutionHistory();
            return result;
        }
    }
    async getPollutionScore(): Promise<PollutionScore | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPollutionScore();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPollutionScore();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSensorHistory(): Promise<Array<SensorHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensorHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensorHistory();
            return result;
        }
    }
    async updateDeviceStatus(arg0: boolean, arg1: boolean, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeviceStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeviceStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSensorReading(arg0: number, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSensorReading(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSensorReading(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AlertSeverity_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PollutionClassification_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollutionClassification): PollutionClassification {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PollutionLevel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollutionLevel): PollutionLevel {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PollutionScore_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollutionScore): PollutionScore {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PollutionScore]): PollutionScore | null {
    return value.length === 0 ? null : from_candid_PollutionScore_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SensorReading]): SensorReading | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DetectionResult]): DetectionResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level: _PollutionLevel;
    score: bigint;
    timestamp: _Timestamp;
    classification: _PollutionClassification;
}): {
    level: PollutionLevel;
    score: bigint;
    timestamp: Timestamp;
    classification: PollutionClassification;
} {
    return {
        level: from_candid_PollutionLevel_n13(_uploadFile, _downloadFile, value.level),
        score: value.score,
        timestamp: value.timestamp,
        classification: from_candid_PollutionClassification_n15(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    isAcknowledged: boolean;
    message: string;
    timestamp: _Timestamp;
    severity: _AlertSeverity;
}): {
    id: AlertId;
    isAcknowledged: boolean;
    message: string;
    timestamp: Timestamp;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        isAcknowledged: value.isAcknowledged,
        message: value.message,
        timestamp: value.timestamp,
        severity: from_candid_AlertSeverity_n6(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): PollutionLevel {
    return "Low" in value ? PollutionLevel.Low : "High" in value ? PollutionLevel.High : "Medium" in value ? PollutionLevel.Medium : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HighlyPolluted: null;
} | {
    Moderate: null;
} | {
    Clean: null;
}): PollutionClassification {
    return "HighlyPolluted" in value ? PollutionClassification.HighlyPolluted : "Moderate" in value ? PollutionClassification.Moderate : "Clean" in value ? PollutionClassification.Clean : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): AlertSeverity {
    return "low" in value ? AlertSeverity.low : "high" in value ? AlertSeverity.high : "critical" in value ? AlertSeverity.critical : "medium" in value ? AlertSeverity.medium : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AlertSeverity_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): _AlertSeverity {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == AlertSeverity.low ? {
        low: null
    } : value == AlertSeverity.high ? {
        high: null
    } : value == AlertSeverity.critical ? {
        critical: null
    } : value == AlertSeverity.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
